### PR TITLE
fixed showing list of registered non static jobs and doc updated

### PR DESCRIPTION
**Pull request by petrparolek**

### CODE REVIEW

**Comment by f3l1x** [comment]
Phpstan is failing.

**Comment by petrparolek** [comment]
do you have any ideas to fix it?

**Comment by mabar** [comment]
Seems like phpstan don't understand callable array syntax. Just put it in phpstan ignored errors

**Comment by petrparolek** [comment]
@mabar thx, fixed

**Comment by f3l1x** [comment]
Thanks.

**Pull request merged**
